Excersise 2
vladk/android-academy pull request #2
Opened 2018-10-01 13:27 UTC by vladk

2018-10-03 08:05 UTC, user32338 requested changes

2018-10-03 08:05 UTC, user32338 commented on Hw2/app/src/main/res/layout-land/activity_main.xml
> +            android:layout_height="@dimen/author_image_height_land"
тут нажно match_parent что бы высота картинки была = высоте экрана иначе для всех экранов надо будет задать ее

2018-10-03 08:05 UTC, user32338 commented on Hw2/app/src/main/res/layout-land/activity_main.xml
> +            android:layout_height="@dimen/author_image_height_land"
+ на маленьких экранах она уменьшиться, а на больших растянется => нужен scaleType что бы было красиво

2018-10-03 10:44 UTC, vladk commented on Hw2/app/src/main/res/layout-land/activity_main.xml
> +            android:layout_height="@dimen/author_image_height_land"
сделал картинку по высоте экрана

2018-10-04 15:38 UTC, user32338 approved these changes
дз2 принято)

2018-10-04 15:38 UTC, merged