Домашнее задание 4 - часть 1
vladk/android-academy pull request #5
Opened 2018-10-14 07:52 UTC by vladk

2018-10-16 06:23 UTC, user32338 requested changes
есть мелкие замечания

2018-10-16 06:23 UTC, user32338 commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +        textView.get().setText(text);
и вот тут мы выхватим NPE ведь WeakReference нам может вернуть null

2018-10-16 06:23 UTC, user32338 commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +            this.mainActivity.get().updateTextView("Left step");
аналогичное NPE

2018-10-16 06:23 UTC, user32338 commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +        stepTextView = findViewById(R.id.step_id);
это больше теория, но может случится так что stepTextView может оказаться еще null пока какой-то из тредов отработает, но скорее всего конечно этого не будет, чисто теоритически, но лучше все таки наверх)

2018-10-16 06:23 UTC, user32338 commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +class TextUpdateRunnable implements Runnable {
а этот дружок у тебя нигде не исаользуется + setText из другого потока не из Main == ошибка >_<

2018-10-16 18:28 UTC, vladk commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +            this.mainActivity.get().updateTextView("Left step");
исправил

2018-10-16 18:28 UTC, vladk commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +        stepTextView = findViewById(R.id.step_id);
исправил

2018-10-16 18:28 UTC, vladk commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +        textView.get().setText(text);
исправил

2018-10-17 10:38 UTC, vladk commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +class TextUpdateRunnable implements Runnable {
используется, из главного потока: runOnUiThread(new TextUpdateRunnable(stepTextView, text));

2018-10-19 15:38 UTC, user32338 commented on app/src/main/java/ru/kononov/vlad/exercise4/MainActivity.java
> +class TextUpdateRunnable implements Runnable {
а не заметил

2018-10-19 15:38 UTC, user32338 approved these changes

2018-10-20 09:51 UTC, merged